spring:
  application:
    name: tqtadka-platform

  datasource:
    url: jdbc:postgresql://localhost:5432/tqtadka_db
    username: tqtadka_user
    password: tqtadka123
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: TQTADKA-HikariCP

  jpa:
    open-in-view: false
    show-sql: true

    hibernate:
      ddl-auto: update   # ⬅️ IMPORTANT (see explanation below)

    properties:
      hibernate:
        default_schema: tqtadka
        format_sql: true
        jdbc:
          time_zone: UTC

server:
  port: 8002

logging:
  level:
    org.springframework.security: DEBUG

# =========================
# LOCAL CDN (DEV / FALLBACK)
app:
  upload-dir: /Users/surajkhanpinjar/tqtadka/uploads

# =========================
# Cloudflare R2 (PROD CDN)
# =========================
cloudflare:
  r2:
    bucket: tqtadka-images
    endpoint: https://36c9a2d1aec1384629ed8efc2d712f61.r2.cloudflarestorage.com
    public-url: https://img.tqtadka.in
